version: '2'

services:
  rest_app:
    build: .
    image: rest_app
    container_name: rest_app
    ports:
      - '${PORT}:${PORT}'
    environment:
      - APP_ADDRESS
      - PORT
      - CELERY_BROKER
      - CELERY_BACKEND
    depends_on:
      - redis

  celery:
    image: rest_app
    command: celery -A celery_app worker --loglevel=debug
    user: nobody
    environment:
      - CELERY_BROKER
      - CELERY_BACKEND
    depends_on:
      - rest_app
      - redis

  redis:
    image: redis:3.2.11
    ports:
      - "6379:6379"

  monitor:
    image: rest_app
    ports:
      - '5555:5555'
    command:  flower -A celery_app --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - rest_app
      - redis