version: '2'

services:
  rest_app:
    build: .
    image: rest_app
    restart: always
    volumes:
      - ./data:/usr/src/ml_data/data:rw
    depends_on:
      - redis
      - mongo
    env_file:
      - '.env'
    ports:
      - '${PORT}:${PORT}'

  celery:
    build: .
    image: rest_app
    restart: always
    volumes:
      - ./data:/usr/src/ml_data/data:rw
    depends_on:
      - rest_app
      - redis
      - mongo
    user: nobody
    env_file:
      - '.env'
    command: celery -A ml_data.celery_app worker --loglevel=info

  redis:
    image: redis:3.2.11
    restart: always
    ports:
      - '6379:6379'

  mongo:
    image: mongo:4.0.4
    volumes:
      - mongodb_volume:/data/db
    restart: always
    ports:
      - '27017:27017'

volumes:
  mongodb_volume:
