swagger: '2.0'
info:
  title: '{{title}}'
  version: '{{version}}'
paths:
  /download/text:
    post:
      operationId: api.download_text
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/UrlSchema'
      responses:
        200:
          description: Downloading text from url
          schema:
            $ref: '#/definitions/StatusResponse'
        400:
          description: Invalid request body
          schema:
            $ref: '#/definitions/StatusResponse'
#    get:
#      operationId: api.fetch_text
  /download/images:
    post:
      operationId: api.download_images
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/UrlSchema'
      responses:
        200:
          description: Downloading images from url
          schema:
            $ref: '#/definitions/StatusResponse'
        400:
          description: Invalid request body
          schema:
            $ref: '#/definitions/StatusResponse'
    #    get:
    #      operationId: api.fetch_images
  /download:
    # get:
    # operationId: api.fetch_all
  /task/{}:
    get:
      operationId: api.check_task
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            $ref: '#/definitions/TaskSchema'
      responses:
        200:
          description: Task_id checked
          schema: {type: string}
definitions:
  UrlSchema:
    properties:
      url:
        type: string
      required: [url]
    type: object
  TaskSchema:
    properties:
      task_id:
        type: string
      required: [task_id]
    type: object
  StatusResponse:
    properties:
      message:
        type: string
      title:
        type: string
      type: object
