swagger: '2.0'
info:
  title: '{{title}}'
  version: '{{version}}'
paths:
  /download/text:
    post:
      operationId: api.download_text
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/UrlSchema'
      responses:
        200:
          description: Downloading text from url
          schema:
            $ref: '#/definitions/StatusResponse'
        400:
          description: Invalid request body
          schema:
            $ref: '#/definitions/StatusResponse'
    get:
      operationId: api.fetch_text
      responses:
        200:
          description: Fetching downloaded text
          schema:
            $ref: '#/definitions/StatusResponse'
  /download/images:
    post:
      operationId: api.download_images
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/UrlSchema'
      responses:
        200:
          description: Downloading images from url
          schema:
            $ref: '#/definitions/StatusResponse'
        400:
          description: Invalid request body
          schema:
            $ref: '#/definitions/StatusResponse'
    get:
      operationId: api.fetch_images
      responses:
        200:
          description: Fetching downloaded images
          schema:
            $ref: '#/definitions/StatusResponse'
  /download:
    get:
      operationId: api.fetch_all
      responses:
        200:
          description: Fetching downloaded items
          schema:
            $ref: '#/definitions/StatusResponse'
  /task/{task_id}:
    get:
      operationId: api.check_task
      parameters:
        - in: path
          name: task_id
          required: true
          type: string
      responses:
        200:
          description: Task_id checked
          schema:
            $ref: '#/definitions/StatusResponse'
definitions:
  UrlSchema:
    properties:
      url:
        type: string
    required: [url]
    type: object
  StatusResponse:
    properties:
      message:
        type: string
      title:
        type: string
    type: object
