swagger: '2.0'
info:
  title: '{{title}}'
  version: '{{version}}'
paths:
  /ml/content/text:
    post:
      operationId: api.fetch_text
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/UrlSchema'
      responses:
        202:
          description: Accepted request, downloading text from url
        400:
          description: Invalid request body
    get:
      operationId: api.download_text
      responses:
        200:
          description: Download text fetched from urls
          schema:
            type: file
  /ml/content/text/{task_id}:
    get:
      operationId: api.get_text_task_status
      parameters:
        - in: path
          name: task_id
          required: true
          type: string
      responses:
        200:
          description: Get status of task for given ID
  /ml/content/images:
    post:
      operationId: api.fetch_images
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/UrlSchema'
      responses:
        202:
          description: Accepted request, downloading text from url
        400:
          description: Invalid request body
    get:
      operationId: api.download_images
      produces:
        - application/zip
      responses:
        200:
          description: Download images fetched from urls
          schema:
            type: file
  /ml/content/images/{task_id}:
    get:
      operationId: api.get_image_task_status
      parameters:
        - in: path
          name: task_id
          required: true
          type: string
      responses:
        200:
          description: Get status of task for given ID
  /ml/content:
    get:
      operationId: api.download_all
      produces:
        - application/zip
      responses:
        200:
          description: Download all fetched files
          schema:
            type: file
definitions:
  UrlSchema:
    properties:
      url:
        type: string
    required: [url]
    type: object
